enum {
	BLANK_CHAR = 0,

	PIXO_BODY_E_THEN_S,
	PIXO_BODY_S_THEN_W,
	PIXO_BODY_W_THEN_N,
	PIXO_BODY_N_THEN_E,

	PIXO_BODY_E,
	PIXO_TAIL_E,
	PIXO_TAIL2_E,
	PIXO_CLOSED_HEAD_E,
	PIXO_CLOSED_MOUTH_E,
	PIXO_CLOSED_LIPS_E,
	PIXO_OPEN_HEAD_E,
	PIXO_OPEN_MOUTH_E,
	PIXO_OPEN_MOUTH2_E,
	PIXO_OPEN_LIPS_E,
	PIXO_OPEN_LIPS2_E,

	PIXO_BODY_N,
	PIXO_TAIL_N,
	PIXO_TAIL2_N,
	PIXO_CLOSED_HEAD_N,
	PIXO_CLOSED_MOUTH_N,
	PIXO_CLOSED_LIPS_N,
	PIXO_OPEN_HEAD_N,
	PIXO_OPEN_MOUTH_N,
	PIXO_OPEN_MOUTH2_N,
	PIXO_OPEN_LIPS_N,
	PIXO_OPEN_LIPS2_N,

	PIXO_BODY_W,
	PIXO_TAIL_W,
	PIXO_TAIL2_W,
	PIXO_CLOSED_HEAD_W,
	PIXO_CLOSED_MOUTH_W,
	PIXO_CLOSED_LIPS_W,
	PIXO_OPEN_HEAD_W,
	PIXO_OPEN_MOUTH_W,
	PIXO_OPEN_MOUTH2_W,
	PIXO_OPEN_LIPS_W,
	PIXO_OPEN_LIPS2_W,

	PIXO_BODY_S,
	PIXO_TAIL_S,
	PIXO_TAIL2_S,
	PIXO_CLOSED_HEAD_S,
	PIXO_CLOSED_MOUTH_S,
	PIXO_CLOSED_LIPS_S,
	PIXO_OPEN_HEAD_S,
	PIXO_OPEN_MOUTH_S,
	PIXO_OPEN_MOUTH2_S,
	PIXO_OPEN_LIPS_S,
	PIXO_OPEN_LIPS2_S,
};

#define	PIXO_BODY_N_THEN_W PIXO_BODY_E_THEN_S
#define	PIXO_BODY_E_THEN_N PIXO_BODY_S_THEN_W
#define	PIXO_BODY_S_THEN_E PIXO_BODY_W_THEN_N
#define	PIXO_BODY_W_THEN_S PIXO_BODY_N_THEN_E

