enum {
	BLANK_CHAR = 0,
	PIXO_BODY_E,
	PIXO_CLOSED_HEAD_E,
	PIXO_CLOSED_MOUTH_E,
	PIXO_CLOSED_LIPS_E,
	PIXO_OPEN_HEAD_E,
	PIXO_OPEN_MOUTH_E,
	PIXO_OPEN_MOUTH2_E,
	PIXO_OPEN_LIPS_E,
	PIXO_OPEN_LIPS2_E
};

